version: "0.16"
formatter: "markdown table"
recursive:
  enabled: true
  path: terraform/
sections:
  hide:
  show:
    - providers
    - inputs
    - outputs
    - modules
output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_AUTOMATED_TF_DOCS_BLOCK -->
    {{ .Content }}
    <!-- END_AUTOMATED_TF_DOCS_BLOCK -->
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
