# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "not-so-simple-api-state-544794004724"
    encrypt = true
    key     = "terraform.tfstate"
    region  = "eu-west-1"
  }
}
