---
swagger: "2.0"
info:
  title: "ProcessWords"
basePath: "/test"
schemes:
- "https"
paths:
  /process-word:
    get:
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
        "400":
          description: "400 response"
      x-amazon-apigateway-integration:
        type: "aws"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/${process_lambda_arn}/invocations"
        responses:
          default:
            statusCode: "200"
          ".*Status code 400.*":
            statusCode: "400"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
definitions:
  Empty:
    type: "object"
